name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6.x', '2.7.x', '3.0.x', '3.1.x']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
      - name: Install dependencies
        run: |
          gem --version
          gem install bundler
          bundle --version
          bundle install
      - name: Run test
        run: |
          bundle exec rake
